import JSZip from 'jszip';

export type TweakId = string;
export type VersionId = string;
export type GroupId = 'Graphics' | 'QoL' | 'Fun' | 'Mechanics';

export type ConfigValue = string | number | boolean;

export type CheckboxConfig = {
	type: 'checkbox';
	label: string;
	default: boolean;
};

export type SliderConfig = {
	type: 'slider';
	label: string;
	default: number;
	min: number;
	max: number;
};

export type SelectConfig = {
	type: 'select';
	label: string;
	default: string;
	options: string[];
};

export type ConfigSchema = CheckboxConfig | SliderConfig | SelectConfig;

export type TweakIcon =
	| { kind: 'emoji'; value: string }
	| { kind: 'image'; src: string; alt?: string };

export interface TweakDef {
	id: TweakId;
	name: string;
	description: string;
	icon: TweakIcon;
	group: GroupId;
	configs?: Record<string, ConfigSchema>;
	incompatibleWith?: TweakId[];

	supportedVersions: (v: VersionId) => boolean;
	stargateState: ((config: Record<string, ConfigValue>) => boolean) | boolean;

	filesToDelete?: (modpackVersion: string, config: Record<string, ConfigValue>) => string[];
	modsToDownload?: (
		modpackVersion: string,
		config: Record<string, ConfigValue>
	) => { name: string; url: string; filename: string }[];
	onDownload: (config: Record<string, ConfigValue>, ctx: DownloadContext) => void;
}

export type TweakConfig = Record<string, ConfigValue>;
export type SelectedTweaksMap = Record<TweakId, TweakConfig>;

export class DownloadContext {
	private zip: JSZip;
	private createdFiles = new Set<string>();
	private modifiedFiles = new Set<string>();
	private deletedFiles = new Set<string>();

	constructor(
		readonly version: string,
		private readonly selections: SelectedTweaksMap,
		readonly ALL_TWEAKS: Map<string, TweakDef>
	) {
		this.zip = new JSZip();
	}

	async generate(): Promise<Blob> {
		for (const [id, tweakConfig] of Object.entries(this.selections)) {
			const tweak = this.ALL_TWEAKS.get(id)!;
			for (const mod of tweak.modsToDownload
				? tweak.modsToDownload(this.version, tweakConfig)
				: []) {
				this.createdFiles.add(`.minecraft/mods/${mod.filename}`);
			}
			for (const file of tweak.filesToDelete
				? tweak.filesToDelete(this.version, tweakConfig)
				: []) {
				this.deletedFiles.add(file);
			}
		}

		this.zip.file(
			'.minecraft/gtnh-tweaks.txt',
			`${window.location.href}

This file was generated by GTNH Tweaks.

- Modpack Version:
  - ${this.version}
- Selected Tweaks:
${Object.keys(this.selections)
	.map((id) => `  - ${id}`)
	.sort()
	.join('\n')}
- Created Files:${[...this.createdFiles.values().map((f) => `  - ${f}\n`)]
				.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
				.join('')}
- Modified files:${[...this.modifiedFiles.values().map((f) => `  - ${f}\n`)]
				.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
				.join('')}
- Deleted Files:${[...this.deletedFiles.values().map((f) => `  - ${f}\n`)]
				.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
				.join('')}
`
		);
		return this.zip.generateAsync({ type: 'blob' });
	}
}
